# Generated by Django 3.2.13 on 2022-10-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app1',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
